### ISSUE TITLE
Invalid XML character (Unicode: 0x0) (NULL)

### ISSUE THREAD

**Issue by splintercell38** [mrombout/Spiner#48] opened 2018-10-14 00:26 UTC
Hi,

This might be related to Issue #43 , but when I try to convert a twine file I get the following error message:

[Fatal Error] :14399:69: An invalid XML character (Unicode: 0x0) was found in the element content of the document.
19:53:39.379 [JavaFX Application Thread] ERROR nl.mikero.spiner.frontend.main.ApplicationView - Could not transform document.
nl.mikero.spiner.core.exception.TwineTransformationFailedException: Could not transform input.
        at nl.mikero.spiner.core.transformer.TransformService.transform(TransformService.java:70)
        at nl.mikero.spiner.frontend.TransformTask.call(TransformTask.java:44)
        at nl.mikero.spiner.frontend.TransformTask.call(TransformTask.java:14)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
Caused by: nl.mikero.spiner.core.exception.ExtendTwineXmlTransformFailedException: org.xml.sax.SAXParseException; lineNumber: 14399; columnNumber: 69; An invalid XML character (Unicode: 0x0) was found in the element content of the document.
        at nl.mikero.spiner.core.twine.extended.ExtendTwineXmlTransformer.transform(ExtendTwineXmlTransformer.java:51)
        at nl.mikero.spiner.core.transformer.TransformService.extend(TransformService.java:99)
        at nl.mikero.spiner.core.transformer.TransformService.transform(TransformService.java:63)
        ... 5 common frames omitted
Caused by: org.xml.sax.SAXParseException: An invalid XML character (Unicode: 0x0) was found in the element content of the document.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at nl.mikero.spiner.core.twine.extended.ExtendTwineXmlTransformer.transform(ExtendTwineXmlTransformer.java:40)

Any idea what might be causing it? The twine .html opens fine but it's possible there are errors in it?

Thanks.

**Comment by mrombout** [comment] 2018-10-14 07:42
Thank you for reporting this issue. Unfortunately I was not able to reproduce this issue using a simple Twine 2.2.1 story setup and the latest 0.1.1 release of Spiner.

Is it perhaps possible for you to share the file so that I can test it with that? Or at least the portion surrounding and including line `14399` as a file (don't copy/paste, as the erroneous character possibly causing this error might disappear)?

**Comment by mrombout** [comment] 2020-06-01 09:18
Closing, since I wasn't able to reproduce this issue.

**Closed by mrombout** 2020-06-01 09:18 UTC
Labels: bug
